# docker-compose up --build -d
version: '3.9'
services:
  skyisopen:
    build:
      context: "."
      args:
        SKYISOPEN_VERSION: 0.0.2-SNAPSHOT
    image: skyisopen
    container_name: skyisopen
    hostname: skyisopen
    ports:
    - '55556:8080'
    restart: always