# docker compose up --build -d
version: '3.9'
services:
  skyisopen:
    container_name: skyisopen
    build:
      context: "."
    image: skyisopen
    hostname: skyisopen
    ports:
    - '55556:8080'
    restart: always
