spring.web.resources.static-locations=classpath:/static/browser/

logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN
logging.level.com.techietable.skyisopen=WARN
